import { SeriesTagKey } from "./enums";
import { SeriesTag } from "./types";

export const SeriesTags: { [key: string]: SeriesTag } = {
  [SeriesTagKey.ACTION]: { key: SeriesTagKey.ACTION, name: "Action" },
  [SeriesTagKey.ADAPTATION]: { key: SeriesTagKey.ADAPTATION, name: "Adaptation" },
  [SeriesTagKey.ADVENTURE]: { key: SeriesTagKey.ADVENTURE, name: "Adventure" },
  [SeriesTagKey.ALIENS]: { key: SeriesTagKey.ALIENS, name: "Aliens" },
  [SeriesTagKey.ANIMALS]: { key: SeriesTagKey.ANIMALS, name: "Animals" },
  [SeriesTagKey.ANTHOLOGY]: { key: SeriesTagKey.ANTHOLOGY, name: "Anthology" },
  [SeriesTagKey.AWARD_WINNING]: {key: SeriesTagKey.AWARD_WINNING,name: "Award Winning",},
  [SeriesTagKey.COMEDY]: { key: SeriesTagKey.COMEDY, name: "Comedy" },
  [SeriesTagKey.COOKING]: { key: SeriesTagKey.COOKING, name: "Cooking" },
  [SeriesTagKey.CRIME]: { key: SeriesTagKey.CRIME, name: "Crime" },
  [SeriesTagKey.CROSSDRESSING]: {key: SeriesTagKey.CROSSDRESSING,name: "Crossdressing",},
  [SeriesTagKey.DELINQUENTS]: { key: SeriesTagKey.DELINQUENTS, name: "Delinquents" },
  [SeriesTagKey.DEMONS]: { key: SeriesTagKey.DEMONS, name: "Demons" },
  [SeriesTagKey.DOUJINSHI]: { key: SeriesTagKey.DOUJINSHI, name: "Doujinshi" },
  [SeriesTagKey.DRAMA]: { key: SeriesTagKey.DRAMA, name: "Drama" },
  [SeriesTagKey.ECCHI]: { key: SeriesTagKey.ECCHI, name: "Ecchi" },
  [SeriesTagKey.FAN_COLORED]: { key: SeriesTagKey.FAN_COLORED, name: "Fan Colored" },
  [SeriesTagKey.FANTASY]: { key: SeriesTagKey.FANTASY, name: "Fantasy" },
  [SeriesTagKey.FULL_COLOR]: { key: SeriesTagKey.FULL_COLOR, name: "Full Color" },
  [SeriesTagKey.GENDERSWAP]: { key: SeriesTagKey.GENDERSWAP, name: "Genderswap" },
  [SeriesTagKey.GHOSTS]: { key: SeriesTagKey.GHOSTS, name: "Ghosts" },
  [SeriesTagKey.GORE]: { key: SeriesTagKey.GORE, name: "Gore" },
  [SeriesTagKey.GYARU]: { key: SeriesTagKey.GYARU, name: "Gyaru" },
  [SeriesTagKey.HAREM]: { key: SeriesTagKey.HAREM, name: "Harem" },
  [SeriesTagKey.HISTORICAL]: { key: SeriesTagKey.HISTORICAL, name: "Historical" },
  [SeriesTagKey.HORROR]: { key: SeriesTagKey.HORROR, name: "Horror" },
  [SeriesTagKey.INCEST]: { key: SeriesTagKey.INCEST, name: "Incest" },
  [SeriesTagKey.ISEKAI]: { key: SeriesTagKey.ISEKAI, name: "Isekai" },
  [SeriesTagKey.JOSEI]: { key: SeriesTagKey.JOSEI, name: "Josei" },
  [SeriesTagKey.LOLI]: { key: SeriesTagKey.LOLI, name: "Loli" },
  [SeriesTagKey.LONG_STRIP]: { key: SeriesTagKey.LONG_STRIP, name: "Long Strip" },
  [SeriesTagKey.MAFIA]: { key: SeriesTagKey.MAFIA, name: "Mafia" },
  [SeriesTagKey.MAGIC]: { key: SeriesTagKey.MAGIC, name: "Magic" },
  [SeriesTagKey.MAGICAL_GIRLS]: {key: SeriesTagKey.MAGICAL_GIRLS,name: "Magical Girls",},
  [SeriesTagKey.MARTIAL_ARTS]: { key: SeriesTagKey.MARTIAL_ARTS, name: "Martial Arts" },
  [SeriesTagKey.MECHA]: { key: SeriesTagKey.MECHA, name: "Mecha" },
  [SeriesTagKey.MEDICAL]: { key: SeriesTagKey.MEDICAL, name: "Medical" },
  [SeriesTagKey.MILITARY]: { key: SeriesTagKey.MILITARY, name: "Military" },
  [SeriesTagKey.MONSTER_GIRLS]: {key: SeriesTagKey.MONSTER_GIRLS,name: "Monster Girls",},
  [SeriesTagKey.MONSTERS]: { key: SeriesTagKey.MONSTERS, name: "Monsters" },
  [SeriesTagKey.MUSIC]: { key: SeriesTagKey.MUSIC, name: "Music" },
  [SeriesTagKey.MYSTERY]: { key: SeriesTagKey.MYSTERY, name: "Mystery" },
  [SeriesTagKey.NINJA]: { key: SeriesTagKey.NINJA, name: "Ninja" },
  [SeriesTagKey.OFFICE_WORKERS]: {key: SeriesTagKey.OFFICE_WORKERS,name: "Office Workers",},
  [SeriesTagKey.OFFICIAL_COLORED]: {key: SeriesTagKey.OFFICIAL_COLORED,name: "Official Colored",},
  [SeriesTagKey.ONESHOT]: { key: SeriesTagKey.ONESHOT, name: "Oneshot" },
  [SeriesTagKey.PHILOSOPHICAL]: {key: SeriesTagKey.PHILOSOPHICAL,name: "Philosophical",},
  [SeriesTagKey.POLICE]: { key: SeriesTagKey.POLICE, name: "Police" },
  [SeriesTagKey.PORNOGRAPHIC]: {key: SeriesTagKey.PORNOGRAPHIC,name: "Pornographic",},
  [SeriesTagKey.POST_APOCALYPTIC]: {key: SeriesTagKey.POST_APOCALYPTIC,name: "Post Apocalyptic",},
  [SeriesTagKey.PSYCHOLOGICAL]: {key: SeriesTagKey.PSYCHOLOGICAL,name: "Psychological"},
  [SeriesTagKey.REINCARNATION]: {key: SeriesTagKey.REINCARNATION,name: "Reincarnation",},
  [SeriesTagKey.REVERSE_HAREM]: {key: SeriesTagKey.REVERSE_HAREM,name: "Reverse Harem",},
  [SeriesTagKey.ROMANCE]: { key: SeriesTagKey.ROMANCE, name: "Romance" },
  [SeriesTagKey.SAMURAI]: { key: SeriesTagKey.SAMURAI, name: "Samurai" },
  [SeriesTagKey.SCHOOL_LIFE]: { key: SeriesTagKey.SCHOOL_LIFE, name: "School Life" },
  [SeriesTagKey.SCI_FI]: { key: SeriesTagKey.SCI_FI, name: "Sci-Fi" },
  [SeriesTagKey.SEINEN]: { key: SeriesTagKey.SEINEN, name: "Seinen" },
  [SeriesTagKey.SEXUAL_VIOLENCE]: {key: SeriesTagKey.SEXUAL_VIOLENCE,name: "Sexual Violence", },
  [SeriesTagKey.SHOTA]: { key: SeriesTagKey.SHOTA, name: "Shota" },
  [SeriesTagKey.SHOUJO_AI]: { key: SeriesTagKey.SHOUJO_AI, name: "Shoujo Ai" },
  [SeriesTagKey.SHOUJO]: { key: SeriesTagKey.SHOUJO, name: "Shoujo" },
  [SeriesTagKey.SHOUNEN_AI]: { key: SeriesTagKey.SHOUNEN_AI, name: "Shounen Ai" },
  [SeriesTagKey.SHOUNEN]: {key: SeriesTagKey.SHOUNEN,name: "Shounen",},
  [SeriesTagKey.SLICE_OF_LIFE]: {key: SeriesTagKey.SLICE_OF_LIFE,name: "Slice of Life",},
  [SeriesTagKey.SMUT]: { key: SeriesTagKey.SMUT, name: "Smut" },
  [SeriesTagKey.SPORTS]: { key: SeriesTagKey.SPORTS, name: "Sports" },
  [SeriesTagKey.SUPERHERO]: { key: SeriesTagKey.SUPERHERO, name: "Superhero" },
  [SeriesTagKey.SUPERNATURAL]: { key: SeriesTagKey.SUPERNATURAL, name: "Supernatural" },
  [SeriesTagKey.SURVIVAL]: { key: SeriesTagKey.SURVIVAL, name: "Survival" },
  [SeriesTagKey.THRILLER]: { key: SeriesTagKey.THRILLER, name: "Thriller" },
  [SeriesTagKey.TIME_TRAVEL]: { key: SeriesTagKey.TIME_TRAVEL, name: "Time Travel" },
  [SeriesTagKey.TRADITIONAL_GAMES]: {key: SeriesTagKey.TRADITIONAL_GAMES,name: "Traditional Games",},
  [SeriesTagKey.TRAGEDY]: { key: SeriesTagKey.TRAGEDY, name: "Tragedy" },
  [SeriesTagKey.USER_CREATED]: {key: SeriesTagKey.USER_CREATED,name: "User Created",},
  [SeriesTagKey.VAMPIRES]: { key: SeriesTagKey.VAMPIRES, name: "Vampires" },
  [SeriesTagKey.VIDEO_GAMES]: { key: SeriesTagKey.VIDEO_GAMES, name: "Video Games" },
  [SeriesTagKey.VILLAINESS]: { key: SeriesTagKey.VILLAINESS, name: "Villainess" },
  [SeriesTagKey.VIRTUAL_REALITY]: {key: SeriesTagKey.VIRTUAL_REALITY,name: "Virtual Reality",},
  [SeriesTagKey.WEB_COMIC]: { key: SeriesTagKey.WEB_COMIC, name: "Web Comic" },
  [SeriesTagKey.WUXIA]: { key: SeriesTagKey.WUXIA, name: "Wuxia" },
  [SeriesTagKey.YAOI]: { key: SeriesTagKey.YAOI, name: "Yaoi" },
  [SeriesTagKey.YONKOMA]: { key: SeriesTagKey.YONKOMA, name: "Yonkoma" },
  [SeriesTagKey.YURI]: { key: SeriesTagKey.YURI, name: "Yuri" },
  [SeriesTagKey.ZOMBIES]: { key: SeriesTagKey.ZOMBIES, name: "Zombies" },
};

export const SeriesTagKeysFromNames = (names: string[]) => {
  return names.map((name: string) => {
    const matching: SeriesTag | undefined = Object.values(SeriesTags).find(
      (tag: SeriesTag) => tag.name === name
    );
    return matching === undefined ? null : matching.key;
  });
};
